# https://docs.npmjs.com/cli/configuring-npm/package-json
$schema: https://json.schemastore.org/package.json
version: 0.0.0
name: "@danielbayley/uproot"
description: Reliable method to find the root path of your git repo, [p]npm/yarn package or app.
keywords:
- root
- project
- path
- find
- toplevel
- top-level
- repository
- git

homepage: https://github.com/danielbayley/uproot#readme
repository: danielbayley/uproot
bugs: https://github.com/danielbayley/uproot/issues

author:
  name: Daniel Bayley
  email: daniel.bayley@me.com
  url: https://danielbayley.dev

license: MIT

type: module
exports: &index ./index.js
files: [*index]

engines:
  node: ">=14.16"
  pnpm: ">=10"
packageManager: pnpm@10.2.0

dependencies:
  "@danielbayley/matchup": ^1.0.2

devDependencies:
  chokidar-cli: ^3.0.0
  fs-fixture: ^2.7.0
  jase: ^1.2.0
  publint: ^0.2.12
  replace-in-file: ^8.2.0
  yaml: ^2.6.1

config:
  yaml-json: yaml --single --json --indent 2
publishConfig:
  access: public
  directory: build #dist
  #linkDirectory: true
  #exports: TODO

scripts:
  prepare: $npm_package_config_yaml_json < package.yaml > package.json

  prepublishOnly: >-
    git stash --include-untracked --keep-index &&
    mkdir -p $npm_package_publishConfig_directory &&
    $npm_package_config_yaml_json < package.yaml |
    jase scripts.prepare --delete > $npm_package_publishConfig_directory/package.json &&
    cp $npm_package_files_0 *.md $npm_package_publishConfig_directory &&

  #prerelease: pnpm prepare
  release: pnpm version
  postrelease: pnpm publish

  #TODO: pnpm pack --json #| jase filename | TODO #npm pack --dry-run
  #pnpm publish *.tgz #danielbayley-uproot-0.0.0.tgz

  version: >-
    replace-in-file version:\ $npm_{old,new}_version package.yaml &&
    git commit --message $npm_new_version package.yaml &&
    git push

  #postpublish: git stash pop --quiet

  watch: chokidar package.yaml --command "pnpm prepare"
  clean: rm -rf package.json $npm_package_publishConfig_directory
  zap: pnpm clean node_modules
